version: '3.6'

services:
  nginx:
    image: nginx:latest
    container_name: prac-nginx
    restart: always
    # ports:
    #   - 0.0.0.0:80:8080
    #   - 0.0.0.0:443:443
    #   # - 0.0.0.0:50051:50051
    # extra_hosts:
    #   - host.docker.internal:host-gateway
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d/:/etc/nginx/conf.d/
      - ./ssl:/etc/nginx/ssl/
      - ./log/:/var/log/nginx/